### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.zoneminder#2]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.zoneminder

- [ ] [E144] common.installedFrom field found in io-package.json. Must be removed.
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E154] common.dependencies must contain [{"js-controller": ">=2.0.0"}] or later - recommended: [{"js-controller": ">=5.0.11"}]
- [ ] [E518] "@alcalzone/release-script" is used, but ".releaseconfig.json" not found
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2023 MeisterTR <meistertr.smarthome@gmail.com>" at the end of README.md
- [ ] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2023 MeisterTR <meistertr.smarthome@gmail.com>" at the start of LICENSE
- [ ] [E816] file tsconfig.json found in repository, but not found in .npmignore

I have also found warnings that may be fixed if possible.

- [ ] [W171] "common.title" is deprecated in io-package.json
- [ ] [W105] "common.titleLang" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] [W109] "common.desc" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] [W156] Adapter should support admin 5 UI (jsonConfig) if you do not use a React based UI
- [ ] [W145] Each "common.news" should be translated into all supported languages (en, de, ru, pt, nl, fr, it, es, pl, uk, zh-cn)
- [ ] [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package

Thanks,
your automatic adapter checker.

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by mcm1957** [comment]
replaced by #487
